### ISSUE TITLE
compiler error: incompatible types

### ISSUE THREAD

**Issue by adamtg** [pkeeper/rt3290sta#1]
Hello.

I am getting this error when compiling in Fedore 20:

rt3290sta/os/linux/../../os/linux/rt_linux.c: In function ‘__RtmpOSFSInfoChange’:
rt3290sta/os/linux/../../os/linux/rt_linux.c:1136:20: error: incompatible types when assigning to type ‘int’ from type ‘kuid_t’
   pOSFSInfo->fsuid = current_fsuid();
                    ^
rt3290sta/os/linux/../../os/linux/rt_linux.c:1137:20: error: incompatible types when assigning to type ‘int’ from type ‘kgid_t’
   pOSFSInfo->fsgid = current_fsgid();
                    ^
This is from commit 51733e56d1af72e2d59e8d6742ae5c3d696e2743 (head as of today)

thank you

**Comment by pkeeper** [comment]
Fixed for me (in master)
confirm please

**Comment by adamtg** [comment]
cloned the head, recompiled, and everything work fine.  Thank you!
